safe-global/safe-react-apps

.travis.yml
travis/prepare_production_deployment.sh

Add Travis CI configuration and scripts.

Add travis CI config and scripts

---

.travis.yml

Remove cache_control from S3 objects, use CDN's default cache control

Remove cache_control from S3 objects, use CDN's default cache control

---

.env.example
.travis.yml
package.json
src/apps/Compound/config.ts
src/apps/Compound/index.tsx
yarn.lock

Do not merge, we need to update yarn.lock once new SDK is published

SDK update

---

src/apps/Compound/index.tsx
src/apps/Compound/tokensTransfers.ts

Closes https://github.com/gnosis/safe-react/issues/901

Compound: feedback fixes

---

src/apps/TxBuilder/hooks/useServices/interfaceRepository.ts

closes #1258.
This should also fix https://github.com/gnosis/safe-react-apps/issues/29.

TX-Builder: fix filter methods condition

---

package.json
src/apps/TxBuilder/hooks/useServices/interfaceRepository.ts

* TX-Builder: fix filter methods condition (#31)

safe-react-apps release v1.4.1

---

package.json

Fix Compound app theme initialization

Set v1.5.1

---

src/apps/WalletConnect/App.tsx

Fix wallet connect showing incorrect instructions when connected/disconnected (#46 )

Fix WalletConnect instructions when connected/disconnected

---

src/apps/WalletConnect/App.tsx

Fix WalletConnect instructions when connected/disconnected (#47)

Add WalletConnect fix to master

---

package.json
src/apps/TxBuilder/hooks/useServices/interfaceRepository.ts
src/utils.ts
yarn.lock

Feature: TX-Builder - Make it work on xDai

---

.travis.yml

Add instruction for apps deployment on xDai network

Add travis deployment for xDai

---

src/apps/TxBuilder/hooks/useServices/interfaceRepository.ts

Add explorer for EWS and Volta

Add Volta and EWS explorer

---

package.json
src/apps/TxBuilder/hooks/useServices/interfaceRepository.ts

This release only includes a minor fix to add:
Add Volta and EWS explorer (#63)

Release v1.6.1

---

.travis.yml
package.json

Add configuration to deploy safe-apps to staging with EWC/Volta RPC

Add staging deployment for EWC and Volta apps

---

.travis.yml
src/apps/TxBuilder/hooks/useServices/interfaceRepository.ts

- Add EWC/Volta apps build to master
- Set v1.6.2

Add EWC/Volta Build to master

---

.gitignore

This PR:
- Adds .eslintcache to gitignore

Misc: Add .eslintcache to gitignore

---

.github/workflows/deploy.pr.yml
.github/workflows/deployment.yml
apps/compound/package.json
apps/compound/src/components.tsx
apps/tx-builder/package.json
apps/tx-builder/src/components/WidgetWrapper.tsx
apps/wallet-connect/package.json
package.json
yarn.lock

This PR:
- Fixes padding after https://github.com/gnosis/safe-react/pull/1937
- Bump dependencies

Add padding in tx builder, compound apps

---

.github/workflows/deploy.pr.yml
.github/workflows/deployment.yml
apps/wallet-connect/src/App.tsx

Wallet connect - Stay in app banner

---

.github/workflows/deployment.yml

This PR:
- Make use of amazon's `configure-aws-credentials` action to configure credentials

Bug: CI not working because of a change in required AWS credentials

---

apps/tx-builder/src/components/Dashboard.tsx

Closes #124.
Hide the build section until a valid address or ABI is entered in the main input.

Hide builder until a valid address or ABI is entered

---

apps/tx-builder/package.json
apps/wallet-connect/package.json

Publish TX-Builder and WalletConnect compatible versions

Publish TX-Builder and WalletConnect

---

package.json

Basically just the version update commit.

Back merge master into dev

---

.github/ISSUE_TEMPLATE/bug-report.md
.github/ISSUE_TEMPLATE/feature-request.md
.github/PULL_REQUEST_TEMPLATE.md

Add templates for issues and pull requests to have some steps to fill information

Add Github template files for Issues and Bugs

---

apps/tx-builder/src/hooks/useServices/interfaceRepository.ts
apps/tx-builder/src/utils.ts

Resolves #187
Adds RPC and blockchain explorer for Arbitrum

Enable Arbitrum for TX Builder

---

apps/tx-builder/src/components/Builder.tsx
apps/tx-builder/src/components/Dashboard.tsx
package.json
yarn.lock

Resolves #185, resolves https://github.com/gnosis/safe-apps-sdk/issues/254
We are going to get the chain info using the SDK (https://github.com/gnosis/safe-apps-sdk/pull/258)
With the new info we are going to show the correct native token symbol
1) Open Tx-builder
2) Add a contract 
3) Check the labels showing the native token are showing the native one and not always ETH

Get chain info for showing native token symbol

---

apps/compound/src/App.tsx

Compound: correct description

---

apps/tx-builder/src/hooks/useServices/interfaceRepository.ts
apps/tx-builder/src/utils.ts

Resolves #230 
Add RPC and Blockexplorer configuration for Avalanche chain
Load the TX-Builder in Avalanche chain Safe. Check that normal operation is possible

Add RPC and Blockexplorer endpoints for TX-Builder

---

apps/tx-builder/src/components/Builder.tsx

Resolves #242 
We are adding a method for check if we should show de address field
1) Add addresses and check the destination address is prefilled
1) Add abis and check the destination address is showed empty

[TX Builder] Add method for check if we are ready for showing the input

---

apps/drain-safe/package.json
apps/drain-safe/src/__tests__/App.test.js
apps/drain-safe/src/components/App.tsx
apps/drain-safe/src/components/Balances.tsx
apps/drain-safe/src/hooks/use-balances.ts
yarn.lock

Resolves https://github.com/gnosis/safe-react-components/issues/170
We are going to use a new component (https://v4.mui.com/components/data-grid)
By using this new component we can use a checkbox in the header for select/unselect all rows
The component is as well much more accesible when used with screen readers
1) Functionality of drain safe should be kept so a regression here is necessary
2) Check/Uncheck header for seeing all assets being selected/unselected
3) Use a screen reader as voice over to navigate through the cells and check/uncheck rows

[Drain Safe] Update table component

---

apps/drain-safe/package.json
yarn.lock

Forgot to push the last commit  in https://github.com/gnosis/safe-react-apps/pull/245 so the package.json has an incorrect link to a git commit

bump version

---

apps/drain-safe/src/components/App.tsx
apps/drain-safe/src/components/TimedComponent.tsx
apps/drain-safe/src/hooks/useTimeout.ts

Resolves #281 
We are adding the feedback message again and showing it for 5 seconds until automatically disappear
1) Open Drain Safe
2) Send transaction 
3) The message should be showed and kept on screen for 5 seconds

[Drain Safe] Show transaction creation message

---

apps/drain-safe/src/components/App.tsx
apps/drain-safe/src/components/TimedComponent.tsx
apps/drain-safe/src/hooks/use-balances.ts
apps/drain-safe/src/hooks/useTimeout.ts
package.json

Merge back small fixes from release v2.4.0

Mergeback release v2.4.0

---

apps/drain-safe/src/hooks/useWeb3.ts
apps/tx-builder/src/utils.ts

Resolves #303 
Add RPC link for Aurora network
Test that Tx Builder and Drain Safe work as expected

Add Aurora RPC link to Drain Safe and TX Builder

---

apps/compound/src/config.ts

Resolves #341 
We are filtering out the coins with no liquidity

fix(compound): App failing if token liquidity retrieved from REST API is zero

---

.github/workflows/deployment.yml

It solves an issue with AWS configuration in release deployment step
Adds aws configuration to github action

fix: add aws config to action

---

apps/compound/package.json
apps/drain-safe/package.json
apps/ramp-network/package.json
apps/tx-builder/package.json
apps/wallet-connect/package.json

An issue with deployment script name
Change the name of production deployment script

fix: deploy prod hook naming

---

scripts/prepare_production_deployment.sh

Not calling hook based on an unused variable

fix: remove tagged build check

---

scripts/deploy_to_s3_bucket.sh
scripts/prepare_production_deployment.sh

fix: use package version in prod hook

---

.github/actions/release/action.yml
TX-builder eexport.json

Use a custom branch to get release deployment changes from bot

fix: set a custom branch to add Changelogs and versions

---

apps/wallet-connect/src/App.tsx
apps/wallet-connect/src/components/Help.tsx

Resolves https://github.com/gnosis/safe-react-apps/issues/354
By adjusting some styles in the Help component

fix(wallet-connect): wallet connect design adjustments

---

apps/compound/CHANGELOG.md
apps/compound/package.json
apps/drain-safe/CHANGELOG.md
apps/drain-safe/package.json
apps/ramp-network/CHANGELOG.md
apps/ramp-network/package.json
apps/tx-builder/CHANGELOG.md
apps/tx-builder/package.json
apps/wallet-connect/CHANGELOG.md
apps/wallet-connect/package.json

Main bump versions

---

apps/wallet-connect/src/App.test.tsx
apps/wallet-connect/src/App.tsx
apps/wallet-connect/src/components/WalletConnectField.tsx

Resolves #369 
Add some improvements in the help messages indicating a link can be used for connecting apart from the QR

feat(wallet-connect): Help improvements

---

apps/drain-safe/src/components/AddressInput.tsx
apps/tx-builder/src/components/TransactionsBatchList.tsx
apps/tx-builder/src/components/forms/fields/AddressContractField.tsx
apps/tx-builder/src/components/forms/fields/JsonField.tsx
apps/tx-builder/src/components/forms/fields/SelectContractField.tsx
apps/tx-builder/src/components/forms/fields/TextContractField.tsx
apps/tx-builder/src/global.ts
apps/tx-builder/src/pages/Dashboard.tsx

fix(tx-builder): tx-builder design adjustments dev

---

apps/drain-safe/CHANGELOG.md
apps/drain-safe/package.json
apps/tx-builder/CHANGELOG.md
apps/tx-builder/package.json
apps/wallet-connect/CHANGELOG.md
apps/wallet-connect/package.json

Merges version bump to main branch

chore: bump versions in main

---

apps/tx-builder/src/components/CreateNewBatchCard.tsx
apps/tx-builder/src/components/forms/fields/JsonField.tsx
apps/tx-builder/src/components/forms/fields/SelectContractField.tsx
apps/tx-builder/src/global.ts
apps/tx-builder/src/pages/CreateTransactions.tsx

Resolves https://github.com/gnosis/safe-react-apps/issues/395, resolves https://github.com/gnosis/safe-react-apps/issues/394, resolves https://github.com/gnosis/safe-react-apps/issues/396
Fix several minor issues in transaction builder

fix(tx-builder): Minor issues

---

apps/compound/CHANGELOG.md
apps/compound/package.json
apps/drain-safe/CHANGELOG.md
apps/drain-safe/package.json
apps/ramp-network/CHANGELOG.md
apps/ramp-network/package.json
apps/tx-builder/CHANGELOG.md
apps/tx-builder/package.json
apps/wallet-connect/CHANGELOG.md
apps/wallet-connect/package.json

Merge back release changes and changelog to development

Mergback changelog to development

---

LICENSE.md

chore: update LICENSE.md

---

.github/workflows/cla.yml

chore: update cla allowlist

---

apps/drain-safe/src/hooks/useWeb3.ts
apps/tx-builder/src/utils.ts

Resolves #357 #356 
Adding the RPC for Goerli network
1) Test Transaction Builder working on Goerli
2) Test Drain Safe working on Goerli

feat: Enable Goerli in Safe apps

---

apps/drain-safe/src/hooks/useWeb3.ts
apps/tx-builder/src/utils.ts

Resolves  [#462](https://github.com/safe-global/safe-react-apps/issues/462) and #458 
It replaces the old xDAI RPC endpoint with a newest one from GnosisChain.

fix: Update GnosisChain RPC endpoints

---

apps/compound/CHANGELOG.md
apps/compound/package.json
apps/drain-safe/CHANGELOG.md
apps/drain-safe/package.json
apps/ramp-network/CHANGELOG.md
apps/ramp-network/package.json
apps/tx-builder/CHANGELOG.md
apps/tx-builder/package.json
apps/wallet-connect/CHANGELOG.md
apps/wallet-connect/package.json

Mergeback changelog and versioning to development

Mergeback to development

---

.gitignore
apps/tx-builder/src/components/EditableLabel.tsx
apps/tx-builder/src/components/TransactionsBatchList.tsx
apps/tx-builder/src/lib/storage.ts
apps/tx-builder/src/pages/CreateTransactions.tsx
yarn.lock

Resolves #468 
Also minor code fixes (use of `var`, unnecessary `async`, add .idea folder to gitignore)
The reason for the bug was that we pass the batchTitle as a component or a string and in the case of the component it used `props.children` as a name. But the passed component didn't have a `children` prop, only the `filename` prop. Since there are different types of components we pass as `batchTitle` I added if statements to check which one is exactly passed
Test uploading and downloading batches from screens where it is allowed (create a batch, edit batch, review, etc)

fix(tx-builder): uploaded batch files are saved as undefined

---

cypress/integration/drain-account/drain.spec.js
cypress/integration/safe-apps-check.spec.js
cypress/integration/tx-builder/tx-builder.spec.js
cypress/support/index.js

Fix for the the new disclaimer for e2e liveness check for apps

fix: e2e app liveness checks

---

cypress/lib/slack.js

fix: typo in slack message

---

apps/tx-builder/package.json
apps/wallet-connect/src/hooks/useWalletConnect.tsx
package.json
yarn.lock

This PR adds eip712 sign to the wallet connect.
https://github.com/safe-global/safe-apps-sdk/pull/356
It can be tested with https://github.com/safe-global/safe-react/pull/4049
Please check https://github.com/safe-global/safe-react/pull/4049

feat: Add eip712 to the wallet connect

---

apps/tx-builder/package.json
apps/wallet-connect/src/hooks/useWalletConnect.tsx
package.json
yarn.lock

Fixes EIP-712 message param type

fix(wallet-connect): fix eth_signTypedData param

---

apps/tx-builder/CHANGELOG.md
apps/tx-builder/package.json

Merge back release to development

chore(tx-builder): Mergeback to development

---

apps/tx-builder/package.json
apps/wallet-connect/public/manifest.json
apps/wallet-connect/src/hooks/useWalletConnect.tsx
cypress/lib/slack.js
package.json
yarn.lock

- #495 and #501
- #497 
- #494

chore: new release

---

apps/tx-builder/CHANGELOG.md
apps/tx-builder/package.json
apps/wallet-connect/CHANGELOG.md
apps/wallet-connect/package.json

Merge back version bump to dev

chore: mergeback to dev

---

apps/safe-claiming-app/src/components/helpers/NavButtons.tsx
apps/safe-claiming-app/src/components/steps/Government/index.tsx
apps/safe-claiming-app/src/components/steps/Intro/index.tsx
apps/safe-claiming-app/src/components/steps/SafeNavigation/index.tsx
apps/safe-claiming-app/src/config/theme.ts
yarn.lock

Resolves [initial QA findings](https://www.notion.so/bd88bcd59e434424a6a7a4b670595937?v=d19437d8331f497db516ea569ba4d4ce&p=26118eb49a8f45cf83ab78a2f9e04040&pm=s)
- Accordion background colour and padding is smaller on the governence step, as well as small textual tweaks.
- All instances of "web3" are now "Web3"
- Observe new accordion styling on governence step.
- Observe no "web3" instances.

fix: textual tweaks + accordion styling

---

apps/safe-claiming-app/src/components/steps/Claim/ClaimCard.tsx
apps/safe-claiming-app/src/components/steps/Delegate/index.tsx
apps/safe-claiming-app/src/components/steps/Success.tsx

Updates text according to Design files

fix(safe-claiming-app): Text adjustments

---

apps/wallet-connect/src/components/Connecting.tsx

Corrects phrasing issues in Wallet Connect message

chore(wallet-connect): fix phrasing issues

---

apps/wallet-connect/src/hooks/useWalletConnect.tsx

Resolves https://github.com/safe-global/safe-apps-sdk/issues/363
by switching order params

fix(wallet-connect): fix params order for eth_signTypedData

---

apps/compound/CHANGELOG.md
apps/compound/package.json
apps/drain-safe/CHANGELOG.md
apps/drain-safe/package.json
apps/safe-claiming-app/CHANGELOG.md
apps/safe-claiming-app/package.json
apps/tx-builder/CHANGELOG.md
apps/tx-builder/package.json
apps/wallet-connect/CHANGELOG.md
apps/wallet-connect/package.json

chore: main bump versions

---

apps/wallet-connect/package.json
yarn.lock

I just need some change to trigger the build to dev

chore(wallet-connect): update date-fns

---

.github/workflows/deployment.yml
.github/workflows/safe-apps-e2e.yml
README.md
apps/drain-safe/src/utils/test-helpers.tsx

chore: update dev environments

---

apps/wallet-connect/package.json
yarn.lock

Resolves https://github.com/safe-global/safe-apps-sdk/issues/363 🤞 
The fix is in https://github.com/safe-global/safe-apps-sdk/pull/376, this PR just updates the package
1. Connect to https://snapshot-1h5j0xvj0-snapshot.vercel.app/#/
2. Vote on a proposal in `fabien.eth` space

fix(wallet-connect): accept string as an argument for signing typed data

---

apps/wallet-connect/CHANGELOG.md
apps/wallet-connect/package.json

chore(wallet-connect): merge back to development

---

.github/workflows/safe-apps-check.yml
.github/workflows/safe-apps-e2e.yml
README.md
cypress/lib/slack.js
cypress/plugins/index.js

Adding more networks to the liveness tests

feat(e2e): Add more networks to e2e liveness tests

---

.github/workflows/safe-apps-check.yml
.github/workflows/safe-apps-e2e.yml
README.md
apps/tx-builder/src/lib/getAbi.ts
apps/wallet-connect/src/App.test.tsx
apps/wallet-connect/src/hooks/useApps.ts

refactor: migrate gnosis.io to safe.global

---

apps/wallet-connect/src/hooks/useWalletConnect.tsx
apps/wallet-connect/src/utils/analytics.ts

Resolves https://github.com/safe-global/web-core/issues/987
By sending messages to the web-core when wallet connect sessions or transactions are initialialized

feat(wallet-connect): Add tracking for sessions and transactions

---

apps/siwe-delegate-manager/project.json

Adds project.json to create automated siwe changelog

chore(siwe-delegate-manager): add project file to automatic versioning

---

apps/safe-claiming-app/CHANGELOG.md
apps/safe-claiming-app/package.json
apps/siwe-delegate-manager/CHANGELOG.md
apps/siwe-delegate-manager/package.json
apps/siwe-delegate-manager/project.json
apps/tx-builder/CHANGELOG.md
apps/tx-builder/package.json
apps/wallet-connect/CHANGELOG.md
apps/wallet-connect/package.json

Merge back release changes to development

chore: mergeback to development

---

apps/mmi/src/App.tsx
apps/mmi/src/index.tsx
apps/mmi/src/lib/mmi.ts
apps/mmi/src/theme.ts

Resolves #574 
Now that MMI extensions seems to support accounts changed we are taking advantage of this for showing related errors

fix(mmi): Verify signature and owner change

---

apps/mmi/src/App.tsx
apps/mmi/src/components/AppBar.tsx
apps/mmi/src/lib/utils.ts

Adds connected account in header

feat(mmi): Add ethereum account in header

---

apps/safe-claiming-app/src/components/AppSwitch.tsx
apps/safe-claiming-app/src/config/colors-dark.ts
apps/safe-claiming-app/src/config/colors.ts
apps/safe-claiming-app/src/widgets/ClaimingWidget.tsx
apps/safe-claiming-app/src/widgets/SnapshotWidget.tsx
apps/safe-claiming-app/src/widgets/Widget.tsx

Note: This PR should wait for https://github.com/safe-global/safe-react-apps/pull/580 to be merged first.
Resolves https://github.com/safe-global/web-core/issues/1222
Combines both Snapshot and Claiming widgets into one.
Both this branch and `one-governance-widget` from web-core have to run locally to test

feat(safe-claiming-app): One widget

---

apps/safe-claiming-app/src/components/AppSwitch.tsx
apps/safe-claiming-app/src/hooks/useDarkMode.ts

Part of https://github.com/safe-global/web-core/issues/1221
The `useDarkMode` hook reads the theme from the URL's hash instead of from the URL search param

feat(safe-claiming-app): Parse theme from URL hash

---

apps/mmi/package.json
apps/mmi/src/App.tsx
apps/mmi/src/components/AppBar.tsx
apps/mmi/src/components/Identicon.tsx
yarn.lock

Adds identicon and improve error messages

feat(mmi): Add identicon

---

.github/actions/release/action.yml

Add missing input to release action

fix(mmi): Add missing inputs to release action

---

.github/workflows/cla.yml

chore: update contributor license agreement url

---

apps/wallet-connect/src/App.tsx
apps/wallet-connect/src/hooks/useApps.ts

Resolves  "Open Safe App" redirection in the new Web-core ui

fix(wallet-connect): fixed open safe app redirection

---

apps/safe-claiming-app/src/components/AppSwitch.tsx
apps/safe-claiming-app/src/components/steps/Claim/SelectedDelegate.tsx
apps/safe-claiming-app/src/components/steps/SafeNavigation/index.tsx
apps/safe-claiming-app/src/config/colors-dark.ts
apps/safe-claiming-app/src/config/colors.ts
apps/safe-claiming-app/src/config/constants.ts
apps/safe-claiming-app/src/hooks/useDarkMode.ts
apps/safe-claiming-app/src/hooks/useSafeSnapshot.ts
apps/safe-claiming-app/src/hooks/useSnapshotSpace.ts
apps/safe-claiming-app/src/index.tsx
apps/safe-claiming-app/src/widgets/ClaimingWidget.tsx
apps/safe-claiming-app/src/widgets/SnapshotWidget.tsx
apps/safe-claiming-app/src/widgets/Widget.tsx

Resolves https://github.com/safe-global/web-core/issues/969
Epic branch
Test from web-core's deployment https://epic-governance.web-core.pages.dev/

feat(safe-claiming-app): Claiming app widgets

---

apps/safe-claiming-app/src/widgets/ClaimingWidget.tsx

Correct title color of claiming widget

fix(safe-claiming-app): correct title color

---

apps/mmi/package.json

fix(mmi): Error loading fonts

---

apps/safe-claiming-app/src/widgets/ClaimingWidget.tsx

Modifies the claiming CTA copy

fix(safe-claiming-app): modify claiming widget copy

---

apps/safe-claiming-app/src/App.tsx
apps/safe-claiming-app/src/hooks/useSafeTokenAllocation.ts
apps/safe-claiming-app/src/widgets/ClaimingWidget.tsx

Solves loading issue with current deployment where unredeemed allocations caused the NoAirdrop screen to show.

fix(safe-claiming-app): loading state of unredeemed tokens

---

apps/safe-claiming-app/CHANGELOG.md
apps/safe-claiming-app/package.json

Mergeback release to development

chore: mergeback release to development

---

.github/workflows/deployment.yml

Fix a typo in project id for dev environment

fix(wallet-connect): fix project id for dev build

---

.github/workflows/safe-apps-check.yml
.gitignore
cypress.config.js
cypress/e2e/tx-builder/tx-builder.spec.cy.js
cypress/support/e2e.js

Resolves some errors after merging tests to dev

fix(e2e): e2e tests

---

.github/actions/release/action.yml
.github/actions/setup-env/action.yml
.github/workflows/cla.yml
.github/workflows/deployment.yml
.github/workflows/lint.yml
README.md
apps/drain-safe/public/index.html
apps/drain-safe/src/__tests__/sdk-helpers.test.js
apps/drain-safe/src/utils/test-helpers.tsx
apps/ramp-network/README.md
apps/ramp-network/public/index.html
apps/wallet-connect/public/index.html
apps/wallet-connect/public/manifest.json

Uses project unified CLA repository

chore: update CLA action to use unified repo

---

apps/tx-builder/src/lib/simulation/simulation.ts

Disable tx simulation for Celo
Adds Celo chain ID to disabled chains

fix(tx-builder): disable tx simulation in Celo

---

apps/drain-safe/CHANGELOG.md
apps/drain-safe/package.json
apps/mmi/CHANGELOG.md
apps/mmi/package.json
apps/ramp-network/CHANGELOG.md
apps/ramp-network/package.json
apps/safe-claiming-app/CHANGELOG.md
apps/safe-claiming-app/package.json
apps/siwe-delegate-manager/CHANGELOG.md
apps/siwe-delegate-manager/package.json
apps/tx-builder/CHANGELOG.md
apps/tx-builder/package.json
apps/wallet-connect/CHANGELOG.md
apps/wallet-connect/package.json

merge changelog back to development

chore: merge back to development

---

apps/wallet-connect/CHANGELOG.md
apps/wallet-connect/package.json

Mergeback release to development

chore(wallet-connect): back to development

---

apps/tx-builder/src/lib/simulation/simulation.ts

Disable transaction simulation for Base Goerli testnet

fix(tx-builder): disable simulation for Base Goerli

---

apps/drain-safe/package.json
apps/safe-claiming-app/package.json
apps/tx-builder/package.json
apps/tx-builder/src/lib/simulation/simulation.ts
apps/wallet-connect/package.json
apps/wallet-connect/src/hooks/useApps.ts
cypress/e2e/tx-builder/tx-builder.spec.cy.js
package.json
yarn.lock

chore(wallet-connect): new release

---

apps/drain-safe/CHANGELOG.md
apps/drain-safe/package.json
apps/safe-claiming-app/CHANGELOG.md
apps/safe-claiming-app/package.json
apps/tx-builder/CHANGELOG.md
apps/tx-builder/package.json
apps/wallet-connect/CHANGELOG.md
apps/wallet-connect/package.json

Merge versions and changelogs to development

chore: development bump versions

---

cypress/e2e/drain-account/drain.spec.cy.js
cypress/e2e/safe-apps-check.spec.cy.js
cypress/e2e/tx-builder/tx-builder.spec.cy.js

Fix e2e tests that aren't working after the URL format change on web, setting the Safe address as a query param

test: fix tests url format

---

.github/workflows/safe-apps-e2e.yml
cypress/e2e/drain-account/drain.spec.cy.js

* Added more test for drain spec
* Changed the order so that happy paths are first and then unhappy paths

test: adding more tests for drain spec

---

apps/drain-safe/CHANGELOG.md
apps/drain-safe/package.json
apps/tx-builder/CHANGELOG.md
apps/tx-builder/package.json
apps/wallet-connect/CHANGELOG.md
apps/wallet-connect/package.json

Merge changelog to development

chore: merge changelog to development

---

apps/drain-safe/CHANGELOG.md
apps/drain-safe/package.json
apps/tx-builder/CHANGELOG.md
apps/tx-builder/package.json
apps/tx-builder/src/App.tsx
apps/tx-builder/src/components/Banner/index.tsx
apps/tx-builder/src/components/Banner/styles.module.css
apps/tx-builder/src/lib/batches/index.ts
apps/tx-builder/src/lib/local-storage/Storage.ts
apps/tx-builder/src/lib/local-storage/local.ts
apps/tx-builder/src/lib/storage.ts
apps/tx-builder/src/store/transactionLibraryContext.tsx
apps/tx-builder/src/utils.ts
apps/wallet-connect/CHANGELOG.md
apps/wallet-connect/package.json
cypress/e2e/drain-account/drain.spec.cy.js
cypress/e2e/tx-builder/tx-builder.spec.cy.js
cypress/fixtures/balances.json

- https://github.com/safe-global/safe-react-apps/issues/660
- https://github.com/safe-global/safe-react-apps/issues/697

chore(tx-builder): new release

---

apps/tx-builder/CHANGELOG.md
apps/tx-builder/package.json

Backmerge changelog to development

chore(tx-builder): backmerge changelog

---

apps/wallet-connect/package.json
apps/wallet-connect/src/App.test.tsx
apps/wallet-connect/src/hooks/useWalletConnectV2.tsx
yarn.lock

Added [`buildApprovedNamespaces `](https://docs.walletconnect.com/2.0/web/web3wallet/wallet-usage#-namespaces-builder-util) helper function to parsing the required and optional namespaces.
```javascript
const safeChain = `${EVMBasedNamespaces}:${safe.chainId}`
const safeAccount = `${EVMBasedNamespaces}:${safe.chainId}:${safe.safeAddress}`
const safeEvents = requiredEIP155Namespace.events // we accept all events like chainChanged & accountsChanged (even if they are not compatible with the Safe)
const approvedSafeNamespaces = buildApprovedNamespaces({
proposal: params,
supportedNamespaces: {
eip155: {
chains: [safeChain], // only the Safe chain
methods: compatibleSafeMethods, // only the Safe methods
events: safeEvents,
accounts: [safeAccount], // only the Safe account
},
},
})
```

refactor(wallet-connect): Added walletconnect namespaces builder helper function

---

apps/wallet-connect/src/App.test.tsx
apps/wallet-connect/src/hooks/useWalletConnectV2.tsx

We are improving the WC error message for the users to understand the issues with the WC 2.0 services

feat(wallet-connect): Improve WC error message for users

---

apps/tx-builder/src/lib/simulation/simulation.ts

Disable Tenderly simulation on Base chain

fix(tx-builder): disable simulation on base

---

apps/tx-builder/package.json
apps/tx-builder/src/lib/simulation/multisend.ts
yarn.lock

Uses new safe-deployment package and bumps to latest version

chore(tx-builder): bump safe-deployments dependency

---

apps/tx-builder/CHANGELOG.md
apps/tx-builder/package.json

chore: backmerges the changelog

---

apps/tx-builder/CHANGELOG.md
apps/tx-builder/package.json

chore: backmerge changelog

---

apps/tx-builder/CHANGELOG.md
apps/tx-builder/package.json

Mergeback changelog to development

chore: mergeback changelog to development

---

apps/tx-builder/CHANGELOG.md
apps/tx-builder/package.json

chore: mergeback changelog to main

---

.github/actions/release/action.yml
.github/workflows/deployment.yml

Fixes deployment for RAMP network App

fix(ramp-network): fixes deployment ymls

---

.github/workflows/safe-apps-check.yml

Resolves #
- Enable safe-apps tests to run earlier

refactor: update test run schedule to run at earlier time

---

.github/workflows/cla.yml
.github/workflows/safe-apps-check.yml
apps/ramp-network/src/ramp.ts

Release Ramp app

---

.github/workflows/cla.yml
docs/release-procedure.md

- Sign CLA
- Add initial `release-procedures.md`

chore: Add usame-algan to CLA, add release-procedure.md

---

apps/ramp-network/CHANGELOG.md
apps/ramp-network/package.json
apps/tx-builder/CHANGELOG.md

Pushes changelog changes to dev

chore: Backmerge main -> dev

---

.github/workflows/deployment.yml

Add the unbutu latest version back into the deployment.yml again

fix(unbutu-version): change unbutu version on deployment.yml

---

apps/tx-builder/package.json
package.json
yarn.lock

Transaction Builder needs the latest version of safe-deployments.

chore(tx-builder): update safe-deployments

---

.github/workflows/safe-apps-check.yml
apps/tx-builder/CHANGELOG.md
apps/tx-builder/package.json
apps/wallet-connect/CHANGELOG.md
apps/wallet-connect/package.json

We need to disable scheduled safe apps test runs as this is not needed at the moment. 
N/A

refactor: Update workflow

---

apps/tx-builder/src/components/Header.tsx

Fixing the tx-builder doc link

fix(tx-builder): update help article link

---

apps/tx-builder/package.json
apps/tx-builder/src/components/Header.tsx

This PR releases the `update the help article link`
- Open the TX builder app
- Click on the help article icon next to the Transaction builder in the header.
- The article should open.

build: Release v1.18.2 of the TX builder

---

apps/tx-builder/package.json
yarn.lock

chore(tx-builder): upgrade @safe-global/safe-deployments to 1.37.45

chore(tx-builder): upgrade @safe-global/safe-deployments to 1.37.45
