safe-global/safe-react-apps

.travis.yml
Set production build to point to mainnet ethereum provider.
Development and staging builds point to rinkeby ethereum provider.
=> Improve Travis CI env vars for pruction build

package.json
This PR:
- Updates package.json version to 1.2.1
In 1.2.0 it was not updated and v1.2.0 tag is already used, so had to use 1.2.1
=> Bump package.json to 1.2.1

apps/tx-builder/src/global.ts, apps/tx-builder/src/index.tsx, apps/tx-builder/src/typings/custom.d.ts, apps/tx-builder/src/typings/fonts.d.ts, apps/wallet-connect/package.json, apps/wallet-connect/src/global.ts, apps/wallet-connect/src/index.tsx, apps/wallet-connect/src/typings/custom.d.ts, apps/wallet-connect/src/typings/fonts.d.ts, yarn.lock
Closes #76.
When safe-apps were separated on independent projects, we forgot to add GlobalStyles in tx-builder and wallet-connect. That's why wallet-connect is showing the wrong font.
=> Add GlobalStyles in Tx-builder and WC

apps/wallet-connect/src/hooks/useWalletConnect.tsx, apps/wallet-connect/src/utils/strings.ts
This PR:
- Closes https://github.com/gnosis/safe-react-apps/issues/100 by converting addresses to lowercase before comparison
=> [WalletConnect] Compare lowercase addresses for eth_sign

apps/compound/package.json, apps/tx-builder/package.json, package.json, yarn.lock
When merging master to dev there was a bug with eslint job related to `babel-eslint` dependency not found: https://github.com/gnosis/safe-react-apps/pull/102/checks?check_run_id=1987360749
I added this dep to the root package.json in the hope to fix it
=> dep bump that hopefully fixes eslint job

.github/workflows/cla.yml
- Update cla link to the one we have on gnosis-safe.io website
=> Update cla link

apps/tx-builder/package.json, apps/tx-builder/src/components/Builder.tsx
We are having some limitations on the way that transaction builder can be used. We decided to not show the to field when address was a valid address for interacting, but many people is loading de ABI using MasterCopy address or similar methods.
Restore to input field, even we show a duplicated value to allow people to still use the transaction builder this way
=> [TX-Builder] Always show to field

apps/tx-builder/src/components/Builder.tsx
Fixes #139 parsing correctly negative number on inputs
From web3 > 1.2.5 there is a bug that parse negative numbers incorrectly adding leading 0's before the minus sign when the value is passed as a string.
The encodeFunctionCall expects that the input values are still passed as string, so to avoid this bug without rolling back to a really old version of web3 we can add the leading 0's for numeric values and that way still send the value as a string
=> [Tx-Builder] Fix negative input number

apps/wallet-connect/package.json
WalletConnect is asking dapps to update their integration: https://twitter.com/WalletConnect/status/1422169112751529989
It looks like they are working on v2 (there's a beta published on NPM). Maybe that would be even better but for now, let's just upgrade to the latest package.
=> [WC] Upgrade the client to the latest version

apps/tx-builder/src/components/Builder.tsx
Resolves #155 
Calling the `encodeFunctionCall` method with a string (containing a bool) value cause the encoding to always convert to zeroes so the final transaction always show "True". Seems to be a problem with the typing in `web3` as the signature for the method is:
```
encodeFunctionCall(abiItem: AbiItem, params: string[]): string;
```
But if you send a bool value it works just fine. We are forcing the conversion and is fixed
1) Open Tx Builder inside a safe
2) Follow the steps in #155 and add several transactions with true and false values
3) Submit and check in the final bundle that the values were converted right
Test contract for mainnet: `0xef0881ec094552b2e128cf945ef17a6752b4ec5d`
=> [TX Builder] encodeFunctionCall not working with boolean values properly

apps/tx-builder/src/components/Builder.tsx, apps/tx-builder/src/components/Dashboard.tsx
Resolves #141 
The problem was the component Builder being destroyed when the contract address entered is wrong. We moved the transaction management to the parent so they are kept
1) Open the transaction builder inside a Safe web and add a correct contract address for example 0x39aa39c021dfbae8fac545936693ac917d5e7563 (`mainnet`)
2) Add transactions using the `redeemUnderlying` method for example like in the video in #141 
3) Now enter a wrong address (For example deleting some characters) and then a correct one again
4) Transactions should be kept and when trying to submit the data associated should be ok
=> [TX Builder] Transactions are initialised when entering a contract with a wrong address (Abi not retrieved properly) 

apps/wallet-connect/src/App.tsx, apps/wallet-connect/src/hooks/useWalletConnect.tsx
Resolves #160 
We now are storing independent sessions for each safe address. When the application starts we look for a session in the localStorage to bring the connection live.
We are using a different way to start the `WalletConnect` instance using `session` or `uri` and sending an optional `storageId` prop for allowing the walletconnect client to store the sessions separate.
1) Open different DApps in different browsers (or mobile apps). The DApps should allow to use WalletConnect. For example you can use:
- [Uniswap](https://app.uniswap.org/#/swap)
- [SushiSwap](https://app.sushi.com/es/swap)
- [Cowswap](https://cowswap.exchange/#/swap)
2) Open different instances of the safe WalletConnect app using different safe addreses
3) Copy the QRs codes and paste them in the safe WalletConnect …
=> Disconnect WalletConnect session when changing safes

apps/tx-builder/src/components/ModalBody.tsx
Resolves #194 
Adding a CSS rule for avoiding overflow. We as well added a little margin to separate transactions
1) Open Transaction builder and add some transactions using the contract indicated in the issue
2) Click the send transactions button
3) In the modal, transactions should be visible and not overflowed and the buttons should be clickable
=> Make the transaction detail in the confirm modal break to next line for avoiding overflow

apps/drain-safe/package.json, apps/drain-safe/src/GlobalStyle.ts, apps/drain-safe/src/__tests__/App.test.js, apps/drain-safe/src/components/App.tsx, apps/drain-safe/src/components/Balances.tsx, apps/drain-safe/src/components/CancelButton.tsx, apps/drain-safe/src/components/SubmitButton.tsx, yarn.lock
Resolves #201 
We are changing the UX for excluding tokens. Instead selecting what to exclude now we are going to see a transfer column with all the assets selected by default. Then we can exclude assets by unselecting the corresponding checkbox in the asset row.
The transfer button is enhance as well showing the current status of the selection (Everything or N assets) and is able to detect no assets selected and change to a disable status.
Open a safe-web with the corresponding custom app pointing to the pr deployed url
=> [Drain Safe] Handle exclusions improvements

apps/tx-builder/src/components/Builder.tsx
Resolves #195 
Adding validation for the input value before adding the transaction
1) Add a contract with no abi
2) Enter incorrect values like characters, negatives ... and check you cannot add a transaction after pressing the "Add transaction" button
3) Add correct values and check you can add transactions
=> [TX BUILDER] Add input validation before adding transactions

apps/tx-builder/src/components/Builder.tsx
Resolves #184 
Using the `<Select />` component from the safe-react-components instead a regular input
1) Choose `True` and `False` values from the dropdown and add several transactions using them
2) Send transactions to safe-web and check that the values are correctly propagated
=> Use Select for bool fields

apps/tx-builder/src/components/Builder.tsx
Resolves #226 
The concrete error specified in this issue was not happening anymore but other one arise. When removed the address value the field itself is removed so this PR fixed this other error instead:
https://user-images.githubusercontent.com/1576776/146756577-bfea4903-a753-4b95-932b-0c51afc15b75.mov
1) For the concrete error in this issue => Add an invalid transaction and see the error being showed (There was an error trying to add the transaction). Then add a valid address and click the Add transaction button to see that the error message is not showed anymore
2) Repeat the process but delete the value in the address field as showed in the video. The address field should be kept in the UI
=> Initial value using inputProps for destination address

apps/tx-builder/src/components/Builder.tsx, apps/tx-builder/src/components/Dashboard.tsx
Resolves #228
Most of the styles were fixed in other PRS
In this one we are adding "Invalid" in front of the "ETH value" label when the field has an error. This should be enough for aligning all the styles
1) Open TX Builder
2) Add a contract with no ABI for seeing the ETH value field. Enter a -1 and see how the label change to "Invalid ETH value"
=> [TX BUILDER] Align Field Styles

apps/tx-builder/src/components/Builder.tsx
Resolves #241 
By resetting form field values on method change
1) Open Tx Builder with a contract with ABI and several methods
2) Select one method and fill values
3) Change to other method. Values should be cleaned up
=> [TX Builder] Initialize field values when changing the contract method

apps/drain-safe/src/hooks/use-balances.ts
Resolves #284 
By calculating from the same filtered assets both the selected and the ones showed in the table
1) Open Drain Safe with an account with a native token with value 0 among other assets
2) Check the display message in the button is showing the correct number of assets
=> [Drain Safe] Fix button message

apps/tx-builder/src/hooks/useServices/getAbi.ts, package.json
Resolves #296 
By adding a 10s timeout to the sources HTTP request
1) Enter TX Builder
2) Add a contract an check after 10 seconds we are going to the tx service fallback
=> [TX Builder] Fix source server timeouts

.github/workflows/lint.yml
Resolves https://github.com/gnosis/safe-apps-sdk/issues/276
As part of the [this ticket](v) we are updating the [safe-apps-sdk](https://github.com/gnosis/safe-apps-sdk) dependencies including the [gnosis/safe-react-eslint-plus-action](https://github.com/gnosis/safe-react-eslint-plus-action). These changes include a major `eslint` version bump from 7.x.x to 8.x.x. 
The list of affected Gnosis repos will be:
```
- https://github.com/gnosis/safe-react
- https://github.com/gnosis/safe-react-apps
- https://github.com/gnosis/safe-apps-sdk
- https://github.com/gnosis/safe-react-e2e-tests
- https://github.com/gnosis/safe-react-components
- https://github.com/gnosis/safe-react-gateway-sdk
- https://github.com/gnosis/safe-apps-dev-ui
```
ESLint 8 bring a [lot of …
=> Update eslint action dependency

.github/workflows/deployment.yml, scripts/deploy_to_s3_bucket.sh
After merging #308, the action failed. This PR wants to fix that
There was a missing space in the if statement that checks for a set ENV variable.
Also, in the AWS script it wraps the package version in double-quotes because https://stackoverflow.com/questions/51757107/unknown-options-when-using-aws-s3-mv
in production
=> ci: fix bash script and hardcode ref for release job

.github/PULL_REQUEST_TEMPLATE.md, .github/workflows/conventional-commit-check.yml
Adding a workflow for check the PR titles are conventional commit formatted and therefore we avoid rebasing commit messages before creating releases if we make some mistake
https://github.com/marketplace/actions/semantic-pull-request
After checking this is working fine we can remove the husky for checking the messages as when we are working on PRs is not useful
=> feat: Check if PR titles are conventional commit formatted

.commitlintrc.json, .husky/commit-msg, package.json, yarn.lock
Removes commitlint as we now have a Conventional Commits integrated as an action for merging pull requests
=> chore: Remove conventional commits linter

apps/tx-builder/src/utils.ts
Resolves https://github.com/gnosis/safe-react-apps/issues/316
When encoding bool[] type, if the array contains strings as "true"or "false" the encode result is always true values. We had same issue for normal bool type. 
For resolving this we are going to parse the array en convert the values to proper booleans
=> fix(tx-builder): parse testBoolArray values in a different way as the encode method don't understand strings

.github/workflows/deployment.yml
Solves an issue with wrong naming of inputs in release github action
Update input names for github actions
=> fix: solve github action inputs name

.github/actions/release/action.yml
Resolves naming conflict between main and main/bump-versions
=> fix: fix typo issue

.github/actions/release/action.yml, .github/actions/setup-env/action.yml, .github/workflows/deployment.yml
Solves an issue where some queries to Infura couldn't be resolved
Restores the Infura RPC API configuration in the build steps that require it
- Test that Compound can fetch balances on mainnet
=> fix: missing infura token 

apps/wallet-connect/package.json, apps/wallet-connect/src/hooks/useApps.ts, package.json, yarn.lock
Resolves https://github.com/gnosis/safe-react-apps/issues/374
Using the new  `getCommunicationInfo()` method for get the origin instead `document.ancestorOrigins`
Related PR: https://github.com/gnosis/safe-apps-sdk/pull/303
=> fix(wallet-connect): ancestorOrigins not available in Firefox

apps/drain-safe/src/components/AddressInput.tsx, apps/tx-builder/src/components/TransactionBatchListItem.tsx, apps/tx-builder/src/components/forms/fields/AddressContractField.tsx, apps/tx-builder/src/components/forms/fields/SelectContractField.tsx, apps/tx-builder/src/components/forms/fields/TextContractField.tsx, apps/tx-builder/src/global.ts
Resolves #368
minor fixes in the css (fields, tooltip & transaction item)
1. Hover a button with a tooltip and verify that no border is present.
2. In the transaction form, verify that the distance between fields is ~~24px~~ updated to 26px.
3. In the transaction list, hover and drag & drop background color should follow [the design](https://www.figma.com/file/G7snLqBXWNPANcOj5MhiR7/Transaction-Builder?node-id=832%3A9776) (no grey background)
=> fix(tx-builder): tx-builder design adjustments 

apps/tx-builder/src/pages/Dashboard.tsx
Resolves https://github.com/gnosis/safe-react-apps/issues/359
By setting an empty string in case the return value from tx-service is null/undefined
=> fix(tx-builder): JsonField value when tx service abi returns undefined

apps/tx-builder/src/components/EditableLabel.tsx, apps/tx-builder/src/pages/TransactionLibrary.tsx
Resolves https://github.com/gnosis/safe-react-apps/issues/400
There is a bug in Firefox with contenteditable spans that makes copying the editable content copy the span itself as well
https://stackoverflow.com/questions/26057848/cut-paste-from-to-contenteditable-to-itself-does-not-work-in-firefox
We are changing the span to a div
=> fix(tx-builder): Content editable firefox bug

apps/tx-builder/src/components/TransactionsBatchList.tsx, apps/tx-builder/src/components/modals/DeleteBatchFromLibrary.tsx, apps/tx-builder/src/components/modals/DeleteBatchModal.tsx, apps/tx-builder/src/components/modals/DeleteTransactionModal.tsx
Resolves https://github.com/gnosis/safe-react-apps/issues/399
Changing the content of the delete popup messages because right now is a little confusing regarding if we are deleting the batch from the library or not
=> fix(tx-builder): Change popup texts for making the messages more clear

apps/compound/public/manifest.json, apps/drain-safe/public/manifest.json, apps/ramp-network/public/manifest.json, apps/tx-builder/public/manifest.json, apps/wallet-connect/public/manifest.json
Resolves an issue retrieving safe app info from the gateway
https://github.com/gnosis/safe-client-gateway/blob/1c52acd5dae1615064bfd29b5d78559684344869/src/providers/info.rs#L152
Restoring iconPaths while not changed in the gateway
=> fix: restore iconPath in manifest files

apps/tx-builder/src/lib/interfaceRepository.ts
Resolves #439 
We should check if the object representing ABI items have props
=> fix(tx-builder): Wrong abi input breaks tx-builder

apps/tx-builder/src/hooks/useSimulation.ts, apps/tx-builder/src/pages/ReviewAndConfirm.tsx
Resolves #453 
We are using the useTransactions hook inside the useSimulation one for up to date information not depending on UI state changes
1) Add several transactions and simulate in the Review and confirm
2) After that reorder transactions and simulate again => New simulation should reflect the changes
=> fix(tx-builder): Fix Tenderly simulations not working after reorder (drag&drop)

apps/tx-builder/src/hooks/useSimulation.ts, apps/tx-builder/src/lib/simulation/simulation.ts, apps/tx-builder/src/pages/ReviewAndConfirm.tsx
Resolves #432 
- Hides simulation button on chains where it is not supported
- Adds error feedback when the simulation request fails
1. Open tx builder on an unsupported chain. The simulation button shouldn't be there
2. To test the error feedback, you can run the tx-builder app locally, and there the request will fail
=> fix(tx-builder): simulation not available on some chains but the button is still there

.github/workflows/safe-apps-e2e.yml
The URL for the development branch in the action should be set to https://safe-team.dev.gnosisdev.com/app
=> fix: Add safe web base url to e2e action

.github/workflows/safe-apps-check.yml
Allowing recording in Cypress Dashboard for liveness tests so we can take a look to the runs there
=> feat: Record liveness tests in Cypress Dashboard

apps/wallet-connect/public/manifest.json
Resolves https://github.com/safe-global/safe-apps-sdk/issues/318
As part of the changes included for the new permissions system we need to update the wallet connect app in order to ask for `camera` permissions. In other case it will fail as we [removed the camera from the allow list](https://github.com/safe-global/safe-react/blob/1cfbb78d10a7b73e36de76391ff9d10d43350a75/src/routes/safe/components/Apps/components/AppFrame.tsx#L399) in safe-react
=> feat(wallet-connect): Add permissions to manifest

apps/safe-claiming-app/src/config/constants.ts, apps/safe-claiming-app/src/hooks/useAirdropFile.ts
- Updates the vesting data url
- Adds the governance forum post url
1. Open the safe-claiming-app on a safe that is eligible for the airdrop
2. Observe the app loading
3. Navigate to the screen: Navigating SafeDAO
4. Click on "process"
5. It should open the relevant forum post
=> fix(safe-claiming-app): Update vesting data url, add governance forum post url

apps/safe-claiming-app/src/config/constants.ts
Updates the guardian data and guardian image urls
1. Open the safe-claiming-app with an eligible safe
2. Navigate to the delegate screen
3. Observe guardians being listed with their images
=> fix(safe-claiming-app): Update guardian data and image urls

apps/safe-claiming-app/src/App.tsx, apps/safe-claiming-app/src/components/helpers/Loading.tsx, apps/safe-claiming-app/src/components/helpers/UnsupportedNetwork.tsx, apps/safe-claiming-app/src/components/steps/Claim/index.tsx, apps/safe-claiming-app/src/config/constants.ts, apps/safe-claiming-app/src/hooks/__tests__/useDelegate.test.ts, apps/safe-claiming-app/src/hooks/__tests__/useFetchVestingStatus.test.ts, apps/safe-claiming-app/src/hooks/__tests__/useIsTokenPaused.test.ts, apps/safe-claiming-app/src/hooks/useDelegate.ts, apps/safe-claiming-app/src/hooks/useIsTokenPaused.ts, apps/safe-claiming-app/src/utils/contracts/delegateRegistry.ts
- Adds missing contract addresses for mainnet
- Adds the test delegateId for rinkeby
- Uses the correct addresses and delegateId depending on the `chainId` of the connected safe
1. Open the safe claiming app with an eligible rinkeby safe
2. The app should display the normal flow
3. Select a delegate
4. Observe a tx being created with the test `delegateId`
=> fix(safe-claiming-app): Add missing contract addresses and delegateId

apps/safe-claiming-app/src/components/steps/Claim/index.tsx
Adds new helper text about redeem deadline on claiming step.
Also fixes colors of helper texts on claiming screen
- Open app with eligible safe
- step to claiming screen
- observe new helper text below claiming button
=> fix(claiming-step): adds helper text about deadline

apps/safe-claiming-app/src/hooks/__tests__/useAmounts.test.ts, apps/safe-claiming-app/src/hooks/useAmounts.ts, apps/safe-claiming-app/src/utils/vesting.ts
The block timestamp still caused the same issue in rare cases. The 30 second desync buffer seems more stable.
Substracts fixed 30 seconds from the current timestamp before calculating the vested amount
- open app for safe with user and ecosystem allocation
- use custom claim amount > user allocation
- the gas estimation should not fail
=> fix(safe-claiming-app): amount calculation uses 30 sec buffer

apps/safe-claiming-app/src/components/steps/Delegate/index.tsx, apps/safe-claiming-app/src/hooks/__tests__/useEnsResolution.test.tsx, apps/safe-claiming-app/src/hooks/useEnsResolution.ts
Resolves #540 
- Updates the input field text description
- Validates that the address is not the same as the current safe address
1. Open a safe that is elligible for the airdrop
2. Navigate to the custom delegate screen
3. Input the current safe address
4. Observe a validation error and the next button is disabled
5. Input an ENS that resolves to the current safe address
6. Observe a validation error and the next button is disabled
=> fix(safe-claiming-app): validate custom delegation address

.github/workflows/safe-apps-check.yml
Remove wrong `push` workflow dispatch remaining from testing
=> fix(e2e): Remove `push` workflow dispatch

apps/tx-builder/src/lib/analytics.ts, apps/tx-builder/src/lib/storage.ts, apps/tx-builder/src/store/transactionsContext.tsx
Resolves https://github.com/safe-global/web-core/issues/1126
We are adding some analytics to the Transaction Builder
Check the following Analytics are being sent using the correct [web-core version](https://github.com/safe-global/web-core/pull/1066)
1) 'Submit transactions confirmed' after a transaction is confirmed
2) 'Saved batch' after saving a batch
3) 'Remove batch' after removing a batch
4) 'Update batch' after updating a batch
5) 'Download batch' after pressing the download batch button
6) 'Import batch' after dragging or opening a file containing a batch
=> feat(tx-builder): Add Transaction builder analytics

apps/safe-claiming-app/src/hooks/useDarkMode.ts
Reads the dark mode passed to the Claiming app through a search param instead of `+dark` in the location hash.
Reads the dark mode from `window.location.search`
https://github.com/safe-global/web-core/pull/1219 can be run locally to test this change
=> feat: read dark mode from search query

apps/safe-claiming-app/src/components/steps/Claim/SelectedDelegate.tsx, apps/safe-claiming-app/src/widgets/ClaimingWidget.tsx
- Reduce flickering of widgets while loading
- delegate edit icon does nothing
- Add `minWidth` to Skeleton of voting power widget
- Remove `onClick` handler of `SelectedDelegate` component in widget
Open the widgets in dashboard
(As the url is hard coded: you can edit the attribute in the dom)
https://user-images.githubusercontent.com/2670790/204243919-fdc7121c-4a9c-4bea-8c95-820d9d880d6f.mov
=> fix(safe-claiming-app): fix loading state & remove edit icon from delegate

apps/safe-claiming-app/src/components/AppSwitch.tsx, apps/safe-claiming-app/src/config/constants.ts, apps/safe-claiming-app/src/hooks/useSafeSnapshot.ts, apps/safe-claiming-app/src/hooks/useSnapshotSpace.ts, apps/safe-claiming-app/src/index.tsx, apps/safe-claiming-app/src/widgets/ClaimingWidget.tsx, apps/safe-claiming-app/src/widgets/SnapshotWidget.tsx
Resolves #591 #590 https://github.com/safe-global/web-core/issues/1275
- removes buy-token-button
- rephrases text for no allocation
- fixes loading state to just a themed spinner
- goerli uses `tutis.eth` instead of `safe.eth`
- fixed size for voting power widget
- test governance widgets on goerli
- use a safe without any tokens / allocation
- use a safe which did not redeem all tokens yet
- use a safe with token allocation
- when loading the app witness the spinner (only visible if network is slow)
=> fix(safe-claiming-app): Fixes multiple issues with government widgets

apps/safe-claiming-app/src/hooks/useSafeSnapshot.ts, apps/safe-claiming-app/src/widgets/SnapshotWidget.tsx
The state chip of the snapshot widget did not display the pending state correctly.
- Adds pending state to SnapshotProposal type
- Maps states to correct background colors
- Check the widget on goerli
- Observe pending proposal being displayed correctly
=> fix(safe-claiming-app): Snapshot widget state chip

apps/drain-safe/package.json, apps/safe-claiming-app/package.json, apps/tx-builder/package.json, apps/wallet-connect/package.json, yarn.lock
Bumps `@gnosis.pm/safe-apps-provider` to v0.15.1, which adds support for custom a gas limit to be passed to transactions initiated through the safe app provider. For more information, see: https://github.com/safe-global/safe-apps-sdk/pull/398.
=> chore: Bump `@gnosis.pm/safe-apps-provider` to v0.15.1

apps/safe-claiming-app/src/App.tsx, apps/safe-claiming-app/src/hooks/useSafeTokenAllocation.ts, apps/safe-claiming-app/src/widgets/ClaimingWidget.tsx
Fixes error in current main version where the app showed the "No Airdrop" screen for unredeemed allocations before the deadline was reached.
Fixes a bug in the loading state.
Use a Safe with unredeemed tokens on mainnet: It now correclty displays the claiming steps.
=> chore: release with fix for loading state in safe-claiming-app

apps/safe-claiming-app/src/components/steps/Claim/index.tsx, apps/safe-claiming-app/src/widgets/ClaimingWidget.tsx
Resolves https://github.com/safe-global/safe-react-apps/issues/627
1. Gives the "Claim and delegate" button same height as the input field
2. Make "Voting Power" and "Delegate" parts of claiming widget clickable and navigate to the claiming app
1. Go to Claiming widget in Dashboard.
2. Click Safe icon or tokens value and you should navigate to the Claiming app
3. Click on the Delegate and you should navigate to the Claiming app
=> style(safe-claiming-app): claiming app minor styles

apps/mmi/src/theme.ts, apps/safe-claiming-app/src/components/AppSwitch.tsx, apps/safe-claiming-app/src/index.tsx
Both the claiming app  and MetaMask institutional were not loading the font correctly.
For the claiming app:
- `CSSBaseline` was not embedded inside the `ThemeProvider`
For MMI:
- The font had a wrong URL
Look at the font of both apps.
=> fix(safe-claiming-app,mmi): fixes embedding of DM Sans font

apps/drain-safe/package.json, apps/safe-claiming-app/package.json, apps/tx-builder/package.json, apps/wallet-connect/package.json, apps/wallet-connect/src/hooks/useApps.ts, cypress/e2e/tx-builder/tx-builder.spec.cy.js, package.json, yarn.lock
Adds support for EIP-1271 in the WalletConnect app by updating the related dependencies.
The `safe-apps-provider`, `safe-apps-sdk` and `safe-apps-react-sdk` that support EIP-1271 have been updated.
Prerequisites:
- Open the https://github.com/safe-global/web-core/pull/1162 deployment.
- Run the [EIP-1271 test DApp](https://github.com/5afe/eip-1271-dapp) locally.
- `main` branch can be used to test WC v1
- `wallet-connect-v2` branch can be used to test WC v2 (with the env vars specified in `env.sample`).
Method:
1. Open the WC app in the aforementioned deployment.
2. Connect to the aforementioned test DApp
3. Toggle off-chain signing and attempt to sign a message.
4. Observe the off-chain signing modal.
5. Sign the message.
6. Observe the signed message in the "Signatures" tab of the …
=> feat(wallet-connect): EIP-1271 support

apps/tx-builder/src/components/Header.tsx, apps/wallet-connect/src/components/AppBar.tsx
Note: the links do not yet exist, but will [when the old Intercom is deactivated](https://5afe.slack.com/archives/C03BHKS5K6D/p1681831629917399?thread_ts=1681735283.046149&cid=C03BHKS5K6D). As such, releassing this needs to be aligned with a mobile release.
Resolves https://github.com/safe-global/web-core/issues/1875
All Help Center articles have been updated according to the [new links](https://docs.google.com/spreadsheets/d/1tZk_4EzXT3DOdqf3eGxkEcpO5R4W-22T2ncDbqeN4r4/edit#gid=0).
Observe the header links in the Transaction Builder/WalletConnect Safe Apps working.
=> fix(tx-builder,wallet-connect): update help centre link

apps/tx-builder/src/lib/storage.ts, apps/tx-builder/src/utils.ts
Resolves https://github.com/safe-global/safe-react-apps/issues/660
By using a blob and opening it in a new window (Firefox and Safari) or directly downloading (Chrome).
It is not the perfect solution but CSP policy is not allowing the download from the iframe. This is a [know bug](https://bugzilla.mozilla.org/show_bug.cgi?id=1365502)
1) Test that the generated file is exactly the same and that can be exported/imported
2) Chrome should behave the same downloading the file
3) Firefox and Safari should open a new window showing the file and should allow to download it from there
=> fix(tx-builder): Open a window instead download batch for Safari and Firefox

apps/wallet-connect/package.json, apps/wallet-connect/src/App.test.tsx, apps/wallet-connect/src/hooks/useWalletConnectV2.tsx, yarn.lock
Now Safe chain is no mandatory in the `requiredNamespaces.chains` obj
=> fix(wallet-connect): Enable dApps to use optional chains and avoid session rejection

apps/wallet-connect/package.json, apps/wallet-connect/src/App.test.tsx, apps/wallet-connect/src/hooks/useWalletConnectV2.tsx, yarn.lock
Added new Walletconnect rejection messages
```
Connection refused: the dApp you are using is sending a connection proposal that is incompatible with your Safe Account
```
=> fix(wallet-connect): Improved Walletconnect rejection messages to dApps

.github/workflows/cla.yml
=> chore: fix CLA link

.github/actions/release/action.yml
The release action.yml was missing the input for the ramp network API key.
Adds it to the action.yml
=> fix(ramp-network): add input to release action

apps/ramp-network/package.json, apps/ramp-network/src/App.tsx, apps/ramp-network/src/ramp.ts, yarn.lock
The old sdk was using a deprecated ramp URL. The new SDK fixes this.
The ramp app does not load anymore.
Upgrades ramp sdk to 4.0.4
- Load the Ramp App
- Witness the widget loading now
=> fix(ramp-network): upgrade ramp SDK to 4.0.4

apps/ramp-network/package.json, apps/ramp-network/src/App.tsx, apps/ramp-network/src/ramp.ts, apps/tx-builder/package.json, package.json, yarn.lock
[chore: bump axios from 1.4.0 to 1.6.0](https://github.com/safe-global/safe-react-apps/commit/601c7cd3e9d42ff93754bbc2f47876daf612091c) (#777)
[fix(ramp-network): upgrade SDK to 4.0.4](https://github.com/safe-global/safe-react-apps/commit/87fd5eb1c277d87fec8c3b8f5b157f44b2e7ec82) (#778 )
=> chore: new release

.github/workflows/cla.yml, apps/ramp-network/src/ramp.ts
Resolves #784
- Add the following chains to the allowed list:
- Arbitrum
- Base
- Celo
- zkSync Era
- zkEVM
- Try to use the Ramp safe app while in a wallet using each of the chains above.
- The app will load without any errors.
Docs: https://docs.ramp.network/assets
=> feat: add support for additional chains on ramp

apps/tx-builder/package.json, apps/tx-builder/src/hooks/useAsync.ts, apps/tx-builder/src/hooks/useSimulation.ts, apps/tx-builder/src/lib/simulation/simulation.ts
Instead of using a hardcoded list of chains where simulation isn't supported, use CGW/config service to get the config of the current chain and check its features list.
I've replaced a hardcoded array of chain ids with an async call to CGW. I've added `useAsync` from the wallet repo for this.
=> feat(tx builder): use cgw for simulation configs

apps/ramp-network/src/ramp.ts
Resolves #811
Add support for Optimism and Linea.
Open the app on those two chains.
=> feat(ramp): add Optimism and Linea

apps/tx-builder/src/components/forms/SolidityForm.test.tsx, apps/tx-builder/src/components/forms/fields/SelectContractField.tsx
A user complained that a select offers a subpar UX when searching for a method name.
Replaces the Select component with an input with Autocomplete.
* Open Transaction Builder
* Enter a contract address with many methods
* Type the first letters of the method name
=> feat(tx-builder): autocomplete for contract method

apps/tx-builder/src/lib/interfaceRepository.ts
=> fix(tx-builder): fix contract method filtering

apps/tx-builder/package.json, yarn.lock
fix: Transaction Builder needs the latest version of safe-deployments for simulation on the latest chains.
=> chore(tx-builder): bump safe-deployments to version 1.37.30
